name: Build and Release Electron App

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build the Electron app
      run: npm run make

    - name: Package the Electron app
      run: npm run package

    - name: Archive the build on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: zip -r app-linux.zip ./dist

    - name: Archive the build on Windows
      if: matrix.os == 'windows-latest'
      run: powershell Compress-Archive -Path ./dist/* -DestinationPath app-windows.zip

    - name: Archive the build on macOS
      if: matrix.os == 'macos-latest'
      run: zip -r app-macos.zip ./dist

    - name: Upload the build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.os }}
        path: |
          app-linux.zip
          app-windows.zip
          app-macos.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download the build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-${{ matrix.os }}
        path: ./builds

    - name: Edit release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./builds/app-linux.zip
          ./builds/app-windows.zip
          ./builds/app-macos.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
