name: Build and Release Electron App

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30  # Increased timeout
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Consider updating to a more recent LTS version if possible

    - name: Install dependencies
      run: |
        npm install

    - name: Install setuptools
      if: matrix.os == 'macos-latest'
      run: pip3 install setuptools

    - name: Package and Build the Electron app
      run: |
        npm run package
        npm run make

    - name: Archive the build
      run: |
        mkdir artifacts
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          cp -R out/make/* artifacts/
        elif [ "${{ matrix.os }}" == "windows-latest" ]; then
          powershell Compress-Archive -Path out\make\* -DestinationPath artifacts\app-windows.zip
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          cp -R out/make/*.dmg artifacts/
        fi

    - name: Upload the build artifacts
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: build-${{ matrix.os }}
        path: artifacts

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3  # Updated to v3
      with:
        path: ./builds

    - name: Prepare release assets
      run: |
        mkdir release_assets
        find ./builds -type f -exec cp {} release_assets/ \;

    - name: Edit release
      uses: softprops/action-gh-release@v1
      with:
        files: release_assets/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}